services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    restart: unless-stopped

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-nestjs
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
    volumes:
      - database-rocketseat:/bitnami/postgresql

volumes:
  database-rocketseat: