services:
  api:
    build:
      context: .
      args:
        PORT: ${PORT}
        DATABASE_URL: ${DATABASE_URL}
    container_name: nestjs
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /usr/src/app/node_modules
    stop_signal: SIGINT
    stop_grace_period: 1s
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    command: >
      sh -c "npm install &&
               npx prisma generate &&
               npm run start:dev"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-nestjs
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
    volumes:
      - database-rocketseat:/bitnami/postgresql

volumes:
  database-rocketseat: